@@HEADER@@

#-------------------------------------------------------------------------------
# Global variables.

@@DOCKER_VARS@@

#-------------------------------------------------------------------------------
# Running `make` will show the list of subcommands that will run.

@@MAKE_ALL@@

#-------------------------------------------------------------------------------
# Running tests

.PHONY: test
test:
	bin/phpunit --testsuite all

.PHONY: test-quick
test-quick:
	docker-compose up $(TEST_QUICK)

.PHONY: test-coverage
test-coverage:
	docker-compose up $(TEST_COVER)

.PHONY: test-benchmark
test-benchmark:
	docker-compose up $(TEST_BENCH)

#-------------------------------------------------------------------------------
# PHP build process stuff

@@PHP_BUILD_PROCESS@@

.PHONY: encode
encode:
	mkdir -p resources/
	wget -O resources/iana-character-sets.xml https://www.iana.org/assignments/character-sets/character-sets.xml
	wget -O resources/whatwg-encodings.json https://encoding.spec.whatwg.org/encodings.json
	wget -O resources/icu-convrtrs.txt http://source.icu-project.org/repos/icu/icu/tags/release-58-1/source/data/mappings/convrtrs.txt
	php tools/encode-class.php

#-------------------------------------------------------------------------------
# Documentation tasks

@@PROJECT_DOCS@@

#-------------------------------------------------------------------------------
# Linting and Static Analysis

@@LINTING_STATIC_ANALYSIS@@

#-------------------------------------------------------------------------------
# Git Tasks

@@RELEASE_TASKS@@
